- name: nginx start
  service:
    name: nginx
    state: started

- name: nginx stop
  service:
    name: nginx
    state: stopped

- name: nginx restart
  service:
    name: nginx
    state: restarted
