---
- name: install sudo packages
  tags:
    - users
    - sudoers
  apt:
    name: sudo
    update_cache: yes

- name: Sudoers
  tags:
    - users
    - sudoers
  lineinfile: "path=/etc/pam.d/sshd state=present line='session optional pam_umask.so umask=0002' insertafter='^session    required     pam_limits.so'"

- name: Sudoers
  tags:
    - users
    - sudoers
  lineinfile: "dest=/etc/sudoers state=present regexp='^%sudo' line='%sudo ALL=(ALL:ALL) NOPASSWD:ALL' validate='visudo -cf %s'"

- name: Add system users
  tags:
    - users
  user:
    name: "{{ item.user }}"
    group: "{{ item.group | default('www-data') }}"
    groups: "{{ item.groups | default() }}"
    shell: /bin/bash
    state: present
    home: "/home/{{ item.user }}"
    createhome: yes
  with_items:
  - "{{ system_users }}"

- name: Add authorized_keys
  tags:
    - users
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ lookup('file', 'files/default/users/' + item.user + '.pub' ) }}"
    state: present
  with_items:
  - "{{ system_users }}"
